site_name: Washington University Libraries Web Archiving
theme: cinder
extra_css: [extra.css]
nav:
- Home: index.md
- About: about.md
- Archive-It Admin:
    - Admin Interface: admin.md
    - Support Center: support.md
- Seed Management:
    - Selection and Addition: seeds.md
    - Test Crawls: test-crawls.md
    - Scoping: scoping.md
    - Maintenance: maintenance.md
    - Metadata: metadata.md
- Quality Assurance:
    - New Seed QA: new-seed-qa.md
    - Production Crawl QA: recurring-crawl-qa.md
- Using Our Web Archives: searching.md
- Other Resources: resources.md

